services:
  - type: web
    name: disaster-backend
    env: python
    region: singapore
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
